export const ESITI = [
  "INZIA IL TRATTAMENTO-VENDITA",
  "NESSUNA VENDITA",
  "ATTESA DOCUMENTAZIONE",
  "RICHIAMERA' / RICHIAMARE",
  "NON SI PRESENTA ALL'APPUNTAMENTO",
  "CONSULTO COMMERCIALE/CLINICO",
  "PAZIENTE SANO",
] as const;

export type Esito = (typeof ESITI)[number];

export const OPPORTUNITA_ESITI = ["ESEGUITO", "NON ESEGUITO", "IN ATTESA"] as const;

export const ESITO_COLORS: Record<string, string> = {
  "INZIA IL TRATTAMENTO-VENDITA": "#22c55e",
  "NESSUNA VENDITA": "#ef4444",
  "ATTESA DOCUMENTAZIONE": "#eab308",
  "RICHIAMERA' / RICHIAMARE": "#3b82f6",
  "NON SI PRESENTA ALL'APPUNTAMENTO": "#a855f7",
  "CONSULTO COMMERCIALE/CLINICO": "#ec4899",
  "PAZIENTE SANO": "#d946ef",
  "ESEGUITO": "#22c55e",
  "NON ESEGUITO": "#f97316",
  "IN ATTESA": "#eab308",
};
